### ISSUE TITLE
Link to "Monad Transformer Step by Step" broken

### ISSUE THREAD

**Issue by futtetennista** [write-you-a-scheme-v2/scheme#18]
In the introduction the **Evaluation Monad** section mentions a guide about using monad transformers but its link - https://www.wespiser.com/writings/sources/Transformers.pdf - is broken. I couldn't find that file anywhere on your website, is it still available online?

**Comment by sdiehl** [comment]
You probably want this:

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.71.596&rep=rep1&type=pdf

**Comment by adamwespiser** [comment]
Thank you for your contribution! Fixed with commit 3279bb8d42dbe5dcfdf7e60586907cc74f075089

**Comment by futtetennista** [comment]
Thank you for writing this and for all links to further resources, I'm learning a lot!
