### ISSUE TITLE
Incomplete TOC?

### ISSUE THREAD

**Issue by Zingam** [write-you-a-scheme-v2/scheme#35]
Is the tutorial incomplete or the TOC is wrong: https://www.wespiser.com/writings/wyas/00_overview.html

I mean the Roadmap part is missing the links to the IO chapter etc...

**Comment by Zingam** [comment]
The link to Readme.md on the same page is broken.

**Comment by adamwespiser** [comment]
Thanks, I'll fix this up tonight!

**Comment by adamwespiser** [comment]
Changes pushed to live version
