### ISSUE TITLE
A pdf version of wyas-v2?

### ISSUE THREAD

**Issue by ljvmiranda921** [write-you-a-scheme-v2/scheme#38]
Hi @adamwespiser , first of all thanks a lot for providing a nice upgrade for Write Yourself a Scheme! As a beginner, it helped me grok Haskell and create projects out of it 👍 

I'm just wondering if there would be any .pdf version of this. It may be helpful for someone like me who is not always connected to the internet / prefers reading on a paper print-out.

Thank you so much!

**Comment by adamwespiser** [comment]
Hello @ljvmiranda921, 
I will loook into this and get back to you. My inclination is to say there should be a way to consolidate everything!

**Comment by ljvmiranda921** [comment]
Okay, thanks a lot! Do I need to close this issue now?

**Comment by louwers** [comment]
Any update on this?

**Comment by adamwespiser** [comment]
Yes, I looked into this: I was able to create a pdf with all the content and pretty good formatting, the only issue is that pandoc doesn't easily support hyperlinks in pdfs. Here's the link: https://github.com/write-you-a-scheme-v2/scheme/blob/master/pdf/WriteYouASchemeVersion2.pdf

@louwers  @ljvmiranda921

**Comment by ljvmiranda921** [comment]
Hi @adamwespiser , I know this Issue is 3 years old, but I'm glad that we're able to resolve this! Many things have changed in three years, just like to share that your work has helped me appreciate Haskell and functional programming even more. No action needed on your end, just want to say thank you!!
