### ISSUE TITLE
some minor doc issues

### ISSUE THREAD

**Issue by ducaale** [write-you-a-scheme-v2/scheme#41]
In https://github.com/write-you-a-scheme-v2/scheme/blob/master/docs/00_overview.md :
1. ``(car '(1 2 3))`` should return `1` instead of `(1)`.
2. ``(cadr '(1 2 3))`` should return `2`  instead of `(2 3)` or `cdr` should be used instead of `cadr`.
3. https://github.com/write-you-a-scheme-v2/scheme/blob/master/Readme.md is not working. the last part should be changed to README.md.
4. https://pages.lip6.fr/Christian.Queinnec/WWW/LiSP.html is not working.

**Comment by adamwespiser** [comment]
4. Link "works on my machine", using Chrome. 
https://pages.lip6.fr/Christian.Queinnec/WWW/LiSP.html.
The rest of these are fixed.
@ducaale Thank you for your contribution
