### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by concastinator** [write-you-a-scheme-v2/scheme#46]
From what I see, 5 years have passed but the last 3 chapters (Standard Library, IO, Conclusions) still have not been addressed (of these, IO being the most important probably). Should the project be considered abandoned, then?

**Comment by adamwespiser** [comment]
I'm still maintaining the project! The chapters/topics you mentioned are available and addressed.

**Comment by adamwespiser** [comment]
Closing this: but you can find the chapters you mentioned on my website, here: https://www.wespiser.com/writings/wyas/home.html

**Comment by concastinator** [comment]
Yep, sorry, a Google search landed me on https://wespiser.com/writings/wyas/00_overview.html which does not contain links to the last 3 chapters. _This_ is what needs to be fixed.
